### ISSUE TITLE
Customize iframe skin through params

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-embed-api#5]
The player supports two additional skins. They can be toggled by adding their class names: `mini` and/or `dark`.

**Version A**

/iframe?slug=200ok&dark=true
/iframe?slug=200ok&dark=true&mini=true

**Version B**

/iframe?slug=200ok&skins=dark
/iframe?slug=200ok&skins=dark,mini

Think I prefer version B as it doesn't require us to hardcode the name of the skins.

In any case, once the params are accepted, we need to add the corresponding class names inside from `embed.html`.

**Comment by hugurp** [comment]
let's wait skins have a stable API in `radio4000-player`
